import XCTest

/// Runs the whole scan in the Simulator from a recorded session, driven by the app's autopilot
/// (`-replay <folder> -autopilot`), and checks that every screen of the flow appears in order,
/// including the gap request. Each screen is screenshotted and accessibility-audited.
///
/// Environment (pass through the scheme's test action, or as TEST_RUNNER_<NAME> to xcodebuild):
/// - HOUSESCAN_REPLAY: a session folder for `testFullFlowFromRealReplay`, and a replacement for the
///   synthetic fixture in `testFullFlowFromReplay`.
/// - HOUSESCAN_SERVER_URL: upload to this server instead of answering with the bundled sample.
/// - HOUSESCAN_AUDIT_REPORT_ONLY=1: record accessibility audit issues as attachments instead of
///   failing, to list every issue in one run. CI leaves it unset, so any issue fails the test.
final class FullFlowUITests: XCTestCase {
    /// Screens in the order the flow must show them.
    static let flow = ["onboarding", "findMeter", "meterCloseUp", "wallWalk", "markFeatures", "gapRequest", "uploading", "spotConfirm", "result", "resultAR"]

    override func setUp() {
        continueAfterFailure = false
    }

    /// The synthetic wall committed with the tests, generated by ios/Tools/make-synthetic-replay.swift.
    static var fixture: String {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appending(path: "Fixtures/synthetic-wall", directoryHint: .isDirectory).path
    }

    /// The same walk recorded as a LiDAR phone would, with depth maps, and a bin standing in front
    /// of the wall 4 to 6 ft right of the meter: `make-synthetic-replay.swift --lidar`.
    static var lidarFixture: String {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appending(path: "Fixtures/synthetic-wall-lidar", directoryHint: .isDirectory).path
    }

    static var environment: [String: String] { ProcessInfo.processInfo.environment }

    @MainActor
    func testFullFlowFromReplay() throws {
        let replay = Self.environment["HOUSESCAN_REPLAY"].flatMap { $0.isEmpty ? nil : $0 } ?? Self.fixture
        try runFlow(replay: replay)
    }

    /// The flow from the LiDAR fixture. Depth must show the bin in front of the wall: the wall map
    /// reports hidden cells on the walk, or, when the autopilot held the bin's frames back for the
    /// gap loop, on the gap request.
    @MainActor
    func testFullFlowFromLidarReplay() throws {
        var showedHidden = false
        try runFlow(replay: Self.lidarFixture) { app, phase in
            guard !showedHidden else { return }
            switch phase {
            // At the autopilot's 3x the walk plays in about 6 s. No other frame sees the wall
            // behind the bin, so its cells stay hidden once the bin has been in view.
            case "wallWalk": showedHidden = Self.wallTapeShowsHidden(app, timeout: 60)
            case "gapRequest": showedHidden = Self.wallTapeShowsHidden(app, timeout: 30)
            default: break
            }
        }
        XCTAssertTrue(showedHidden, "the wall map never reported hidden cells behind the bin")
    }

    /// Device run 1's failure on the synthetic replay (`-autopilotCantGetThere`): "Can't get there"
    /// goes to the ground by the meter before it is seen, then ends each side where the walk went
    /// farthest, 5 m left and right of the meter (16 ft 5 in). The old rule put the ends at the
    /// unbroken covered reach, 2.5 ft here, and the export left out everything past it. The ends
    /// must land within a keyframe's spacing (0.5 m, 1.6 ft) of the phone, and the scene must
    /// report the wall and the ground the walk saw, the ground by the meter included.
    @MainActor
    func testCantGetThereEndsWhereThePhoneIs() throws {
        var tape = ""
        var scene: [String: Any] = [:]
        try runFlow(replay: Self.fixture, extraArguments: ["-autopilotCantGetThere"], beforeLeaving: { app, phase in
            guard phase == "wallWalk" else { return }
            // The value that matched, from one read: the map's element is rebuilt as the walk
            // goes on, so a second read could find it gone.
            let ended = ElementRead.waitForValue(of: app.descendants(matching: .any)["wallTape"], timeout: 90) {
                $0.contains("Left end") && $0.contains("Right end")
            }
            XCTAssertNotNil(ended, "the walk never ended both sides")
            tape = ended ?? ""
        }, onScene: { data, _ in
            scene = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
        })
        // The wall map says where each end is, in words VoiceOver reads.
        XCTAssertTrue(tape.contains("Left end ") && tape.contains("left of your meter") && tape.contains("Right end "), "wall map: \(tape)")

        // Ends: the baseline's end points as distances along it from the meter, in feet.
        let walls = try XCTUnwrap(scene["walls"] as? [[String: Any]])
        XCTAssertEqual(walls.count, 1)
        let baseline = try XCTUnwrap(walls.first?["baseline"] as? [[Double]])
        let meterPos = try XCTUnwrap((scene["meter"] as? [String: Any])?["pos"] as? [Double])
        let first = try XCTUnwrap(baseline.first), last = try XCTUnwrap(baseline.last)
        let length = hypot(last[0] - first[0], last[1] - first[1])
        let along = { (p: [Double]) in ((p[0] - meterPos[0]) * (last[0] - first[0]) + (p[1] - meterPos[2]) * (last[1] - first[1])) / length }
        XCTAssertEqual(along(first), -16.40, accuracy: 1.7, "left end")
        XCTAssertEqual(along(last), 16.40, accuracy: 1.7, "right end")
        let coverage = try XCTUnwrap(scene["coverage"] as? [String: Any])
        let ends = try XCTUnwrap(coverage["ends"] as? [String: [String: String]])
        XCTAssertEqual(ends["left"]?["kind"], "unexplored")
        XCTAssertEqual(ends["right"]?["kind"], "unexplored")

        let observed = try XCTUnwrap(coverage["observed"] as? [[String: Any]])
        func spans(_ band: String) -> [[Double]] { observed.filter { $0["band"] as? String == band }.compactMap { $0["span_ft"] as? [Double] } }
        let wall = spans("wall"), ground = spans("ground")
        XCTAssertFalse(wall.isEmpty, "no wall observed: \(observed)")
        XCTAssertTrue(ground.contains { $0[0] <= 0 && $0[1] >= 0 }, "no ground observed by the meter: \(ground)")
        XCTAssertTrue(ground.contains { $0[0] < -10 }, "no ground observed past 10 ft left: \(ground)")
        XCTAssertTrue(ground.contains { $0[1] > 10 }, "no ground observed past 10 ft right: \(ground)")
        let attachment = XCTAttachment(string: "wall map: \(tape)\nends: \(along(first)) ft, \(along(last)) ft\nobserved: \(observed)")
        attachment.name = "cantGetThere-scene"
        attachment.lifetime = .keepAlways
        add(attachment)
    }

    /// "Something's there" on the spot check (`-autopilotSomethingThere`): the scan stops claiming
    /// the spot's clearance area and goes to the server again, and the flow still ends on the
    /// result, which says what the homeowner answered. The scene the last upload sent, and the one
    /// the app exports at the result, list no wall, ground or facing entry over the stretch the
    /// refusal withdrew (whole cells, as the autopilot reports them in `spot-refusal.json`), and
    /// still list both bands elsewhere. The uploaded scene is attached as
    /// `somethingThere-uploaded-scene` for the schema check.
    @MainActor
    func testSomethingThereChecksTheWallAgain() throws {
        var sawPhoto = false
        var sawRefusal = false
        var scenes: [String: [String: Any]] = [:]
        var withdrawn: [Double] = []
        try runFlow(replay: Self.fixture, extraArguments: ["-autopilotSomethingThere"], beforeLeaving: { app, phase in
            switch phase {
            case "spotConfirm":
                sawPhoto = ElementRead.snapshot(app.descendants(matching: .any)["spot.photo"])?.label == "Photo of your wall"
            case "result":
                sawRefusal = app.descendants(matching: .any)["result.spotRefused"].exists
            default: break
            }
        }, onScene: { data, gate in
            let refusal = try Data(contentsOf: gate.appending(path: "spot-refusal.json"))
            withdrawn = try XCTUnwrap((JSONSerialization.jsonObject(with: refusal) as? [String: Any])?["withdrawn_span_ft"] as? [Double])
            let uploaded = try Data(contentsOf: gate.appending(path: "uploaded-scene.json"))
            let attachment = XCTAttachment(data: uploaded, uniformTypeIdentifier: "public.json")
            attachment.name = "somethingThere-uploaded-scene"
            attachment.lifetime = .keepAlways
            self.add(attachment)
            for (name, bytes) in [("exported", data), ("uploaded", uploaded)] {
                scenes[name] = try XCTUnwrap(JSONSerialization.jsonObject(with: bytes) as? [String: Any])
            }
        })
        XCTAssertTrue(sawPhoto, "the spot check showed no photo of the spot")
        XCTAssertTrue(sawRefusal, "the result doesn't say the homeowner said something stands there")
        XCTAssertEqual(withdrawn.count, 2)
        let low = try XCTUnwrap(withdrawn.first), high = try XCTUnwrap(withdrawn.last)
        XCTAssertGreaterThan(high - low, 1, "withdrawn: \(withdrawn)")
        for (name, scene) in scenes {
            let coverage = try XCTUnwrap(scene["coverage"] as? [String: Any])
            let observed = try XCTUnwrap(coverage["observed"] as? [[String: Any]])
            for band in ["wall", "ground", "facing"] {
                let spans = observed.filter { $0["band"] as? String == band }.compactMap { $0["span_ft"] as? [Double] }
                for span in spans {
                    XCTAssertTrue(span[1] <= low + 1e-3 || span[0] >= high - 1e-3, "\(name) scene: \(band) \(span) reaches into the withdrawn \(low)...\(high)")
                }
                if band != "facing" {
                    XCTAssertFalse(spans.isEmpty, "\(name) scene: no \(band) observed at all")
                }
            }
        }
    }

    /// Practice meter on the synthetic replay: the switch is turned on in the developer options on
    /// the first screen, the close-up stores the drawn sample's photo and the app's own reader
    /// reads its number, which the autopilot confirms, and the rest of the flow runs to the AR
    /// result. Every screen after the first carries the "Practice meter" badge. Afterwards Start
    /// over clears the badge and the switch is turned off again for the tests that follow.
    @MainActor
    func testPracticeMeterFromReplay() throws {
        // A failed result assertion must not leave the saved switch on for later tests.
        addTeardownBlock { @MainActor in
            let cleanup = XCUIApplication()
            cleanup.launchArguments = ["-uiDemo", "-uiDemoFreeze"]
            cleanup.launch()
            Self.setPracticeMeter(false, in: cleanup)
            cleanup.terminate()
        }
        var readNumber: String?
        var unbadged: [String] = []
        var app: XCUIApplication?
        try runFlow(replay: Self.fixture, practice: true, beforeLeaving: { running, phase in
            app = running
            if phase == "onboarding" {
                Self.setPracticeMeter(true, in: running)
                return
            }
            if !running.descendants(matching: .any)["practiceBadge"].exists { unbadged.append(phase) }
            if phase == "meterCloseUp" {
                // Offered as a candidate, or already confirmed ("Meter number saved"): either way
                // the reader read it from the sample's photo.
                let number = running.descendants(matching: .any)
                    .matching(NSPredicate(format: "label CONTAINS %@", Self.sampleNumber)).firstMatch
                readNumber = number.waitForExistence(timeout: 30) ? number.label : nil
            }
        })
        XCTAssertNotNil(readNumber, "the reader never offered the sample meter's number \(Self.sampleNumber)")
        XCTAssertEqual(unbadged, [], "screens without the Practice meter badge")

        let running = try XCTUnwrap(app)
        // The redesigned result keeps Start over in Details, below the answer and footnotes.
        Self.tapAfterScrolling(running, "result.details")
        Self.tapAfterScrolling(running, "action.startOver")
        XCTAssertTrue(running.descendants(matching: .any)["screen.onboarding"].waitForExistence(timeout: 15))
        XCTAssertFalse(running.descendants(matching: .any)["practiceBadge"].exists, "the badge outlived the practice scan")
        Self.setPracticeMeter(false, in: running)
    }

    @MainActor
    private static func tapAfterScrolling(_ app: XCUIApplication, _ identifier: String) {
        let target = app.descendants(matching: .any)[identifier].firstMatch
        XCTAssertTrue(target.waitForExistence(timeout: 10), "missing \(identifier)")
        let scroll = app.scrollViews.firstMatch
        XCTAssertTrue(scroll.exists, "the result has no scroll view")
        for _ in 0..<8 {
            if target.isHittable { break }
            scroll.swipeUp(velocity: .slow)
        }
        XCTAssertTrue(target.isHittable, "not tappable after scrolling: \(identifier)")
        target.tap()
    }

    /// `PracticeMeter.number` in HouseScanKit, which the test bundle doesn't link.
    static let sampleNumber = "12345678"

    /// Opens the developer options from the first screen and sets the practice meter switch.
    @MainActor
    static func setPracticeMeter(_ on: Bool, in app: XCUIApplication) {
        let open = app.buttons["action.developerOptions"]
        XCTAssertTrue(open.waitForExistence(timeout: 10), "no developer options on the first screen")
        open.tap()
        let row = app.switches["developer.practiceMeter"]
        XCTAssertTrue(row.waitForExistence(timeout: 10), "the developer options have no practice meter switch")
        let wanted = on ? "1" : "0"
        if row.value as? String != wanted {
            // A Form row's switch is the row; the control inside it takes the tap.
            let control = row.switches.firstMatch
            (control.exists ? control : row).tap()
        }
        let set = NSPredicate(format: "value == %@", wanted)
        XCTAssertEqual(XCTWaiter.wait(for: [XCTNSPredicateExpectation(predicate: set, object: row)], timeout: 5), .completed, "the switch didn't turn \(on ? "on" : "off")")
        let shot = XCTAttachment(screenshot: app.screenshot())
        shot.name = "developerOptions-\(on ? "on" : "off")"
        shot.lifetime = .keepAlways
        XCTContext.runActivity(named: shot.name ?? "") { $0.add(shot) }
        app.buttons["action.closeDeveloperOptions"].tap()
        XCTAssertTrue(app.descendants(matching: .any)["screen.onboarding"].waitForExistence(timeout: 10))
    }

    /// Waits for the wall map's accessibility summary to mention hidden cells; false on timeout.
    @MainActor
    private static func wallTapeShowsHidden(_ app: XCUIApplication, timeout: TimeInterval) -> Bool {
        ElementRead.waitForValue(of: app.descendants(matching: .any)["wallTape"], timeout: timeout) {
            $0.localizedCaseInsensitiveContains("hidden")
        } != nil
    }

    /// Runs only when HOUSESCAN_REPLAY names a session folder, so CI stays on the synthetic fixture.
    /// Its screenshots can show licensed or private imagery: keep them out of git.
    @MainActor
    func testFullFlowFromRealReplay() throws {
        guard let replay = Self.environment["HOUSESCAN_REPLAY"], !replay.isEmpty else {
            throw XCTSkip("Set HOUSESCAN_REPLAY to a measure-lab-session folder to run this test.")
        }
        try runFlow(replay: replay)
    }

    /// Audits the screen twice, six seconds apart, and fails on the issues found both times
    /// (`AccessibilityAudit.run`).
    ///
    /// The walk keeps taking photos while it is audited, so the photo count's number is often
    /// mid-roll, and the result's text is still fading in when the screen appears. A single audit
    /// reports those passing frames as contrast failures; a real contrast or clipping problem is
    /// still there later. The walk also rebuilds parts of the screen while it is audited, so an
    /// issue's element can be gone before it is read: that one is attached, not failed on. Every
    /// screen state is also audited frozen by ScreenStatesUITests.
    @MainActor
    private func audit(_ app: XCUIApplication, screen: String) throws {
        // Six seconds: long enough for a system notification banner to leave. On CI one slid in
        // over the find-meter screen and failed its contrast check twice a second apart (run
        // 36264789032), as ScreenStatesUITests' audit also allows for.
        let outcome = try AccessibilityAudit.run(app) { _ in Thread.sleep(forTimeInterval: 6.0) }
        if !outcome.unread.isEmpty {
            let note = XCTAttachment(string: outcome.unread.joined(separator: "\n"))
            note.name = "audit-\(screen)-element-gone"
            note.lifetime = .keepAlways
            add(note)
        }
        for (_, finding) in outcome.persistent {
            let text = "screen.\(screen): \(finding.message)"
            if Self.environment["HOUSESCAN_AUDIT_REPORT_ONLY"] == "1" {
                let note = XCTAttachment(string: text)
                note.name = "audit-\(screen)"
                note.lifetime = .keepAlways
                add(note)
                print("AUDIT \(text)")
            } else {
                XCTFail(text)
            }
        }
    }

    /// `beforeLeaving` runs on each screen after its screenshot and audit, while the app still
    /// waits to leave it. `onScene` gets the scene.json the autopilot leaves in the gate folder
    /// once the result shows, and the gate folder for the other files it leaves there.
    ///
    /// The practice meter switch is stored in the app's settings, which outlive a run in the
    /// Simulator. Unless `practice` is set, `-practiceMeter NO` holds it off for this run whatever
    /// an earlier test left there; with it, the test sets the switch itself.
    @MainActor
    private func runFlow(
        replay: String, extraArguments: [String] = [], practice: Bool = false,
        beforeLeaving: (XCUIApplication, String) -> Void = { _, _ in },
        onScene: ((Data, URL) throws -> Void)? = nil
    ) throws {
        let app = XCUIApplication()
        // The app waits for a file per screen in this folder before leaving it, so the audit of a
        // slow screen can never make the test miss the next one.
        let gate = URL(fileURLWithPath: NSTemporaryDirectory()).appending(path: "housescan-gate-\(UUID().uuidString)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: gate, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: gate) }
        var arguments = ["-replay", replay, "-autopilot", "-autopilotHold", "1.5", "-autopilotGate", gate.path] + extraArguments
        if !practice { arguments += ["-practiceMeter", "NO"] }
        if let server = Self.environment["HOUSESCAN_SERVER_URL"], !server.isEmpty {
            arguments += ["-serverURL", server]
        } else {
            // The app defaults to the deployed server; the sample keeps this run offline.
            arguments += ["-sampleResult"]
        }
        app.launchArguments = arguments
        app.launch()

        for phase in Self.flow {
            let screen = app.descendants(matching: .any)["screen.\(phase)"]
            // The walk replays the whole recording; everything else takes seconds.
            let timeout: TimeInterval = phase == "markFeatures" || phase == "result" ? 150 : 60
            XCTAssertTrue(screen.waitForExistence(timeout: timeout), "screen.\(phase) never appeared")
            // Let the entrance animation finish so the screenshot and audit see the settled screen.
            Thread.sleep(forTimeInterval: 1.0)
            let shot = XCTAttachment(screenshot: app.screenshot())
            shot.name = phase
            shot.lifetime = .keepAlways
            add(shot)
            try audit(app, screen: phase)
            beforeLeaving(app, phase)
            if phase == "result", let onScene {
                let file = gate.appending(path: "scene.json")
                let deadline = Date().addingTimeInterval(20)
                while !FileManager.default.fileExists(atPath: file.path), Date() < deadline { Thread.sleep(forTimeInterval: 0.2) }
                try onScene(try Data(contentsOf: file), gate)
            }
            try Data().write(to: gate.appending(path: phase))
        }
        // Closing the AR view returns to the result.
        XCTAssertTrue(app.descendants(matching: .any)["screen.result"].waitForExistence(timeout: 20), "closing AR did not return to the result")
    }
}
