import XCTest

/// Runs the whole scan in the Simulator from a recorded session, driven by the app's autopilot
/// (`-replay <folder> -autopilot`), and checks that every screen of the flow appears in order,
/// including the gap request. Each screen is screenshotted and accessibility-audited.
///
/// Environment (pass through the scheme's test action, or as TEST_RUNNER_<NAME> to xcodebuild):
/// - HOUSESCAN_REPLAY: a session folder for `testFullFlowFromRealReplay`, and a replacement for the
///   synthetic fixture in `testFullFlowFromReplay`.
/// - HOUSESCAN_SERVER_URL: upload to this server instead of answering with the bundled sample.
/// - HOUSESCAN_AUDIT_REPORT_ONLY=1: record accessibility audit issues as attachments instead of
///   failing, to list every issue in one run. CI leaves it unset, so any issue fails the test.
final class FullFlowUITests: XCTestCase {
    /// Screens in the order the flow must show them.
    static let flow = ["onboarding", "findMeter", "meterCloseUp", "wallWalk", "markFeatures", "gapRequest", "uploading", "result", "resultAR"]

    override func setUp() {
        continueAfterFailure = false
    }

    /// The synthetic wall committed with the tests, generated by ios/Tools/make-synthetic-replay.swift.
    static var fixture: String {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appending(path: "Fixtures/synthetic-wall", directoryHint: .isDirectory).path
    }

    static var environment: [String: String] { ProcessInfo.processInfo.environment }

    @MainActor
    func testFullFlowFromReplay() throws {
        let replay = Self.environment["HOUSESCAN_REPLAY"].flatMap { $0.isEmpty ? nil : $0 } ?? Self.fixture
        try runFlow(replay: replay)
    }

    /// Runs only when HOUSESCAN_REPLAY names a session folder, so CI stays on the synthetic fixture.
    /// Its screenshots can show licensed or private imagery: keep them out of git.
    @MainActor
    func testFullFlowFromRealReplay() throws {
        guard let replay = Self.environment["HOUSESCAN_REPLAY"], !replay.isEmpty else {
            throw XCTSkip("Set HOUSESCAN_REPLAY to a measure-lab-session folder to run this test.")
        }
        try runFlow(replay: replay)
    }

    @MainActor
    private func audit(_ app: XCUIApplication, screen: String) throws {
        guard Self.environment["HOUSESCAN_AUDIT_REPORT_ONLY"] == "1" else {
            try app.performAccessibilityAudit()
            return
        }
        try app.performAccessibilityAudit { issue in
            let note = XCTAttachment(string: "screen.\(screen): \(issue.compactDescription) - \(issue.detailedDescription) [\(issue.element?.identifier ?? "")] \(issue.element?.label ?? "")")
            note.name = "audit-\(screen)"
            note.lifetime = .keepAlways
            self.add(note)
            print("AUDIT screen.\(screen): \(issue.compactDescription) | \(issue.element?.label ?? "")")
            return true
        }
    }

    @MainActor
    private func runFlow(replay: String) throws {
        let app = XCUIApplication()
        var arguments = ["-replay", replay, "-autopilot", "-autopilotHold", "3"]
        if let server = Self.environment["HOUSESCAN_SERVER_URL"], !server.isEmpty {
            arguments += ["-serverURL", server]
        } else {
            arguments += ["-sampleResult"]
        }
        app.launchArguments = arguments
        app.launch()

        for phase in Self.flow {
            let screen = app.descendants(matching: .any)["screen.\(phase)"]
            // The walk replays the whole recording; everything else takes seconds.
            let timeout: TimeInterval = phase == "markFeatures" || phase == "result" ? 150 : 60
            XCTAssertTrue(screen.waitForExistence(timeout: timeout), "screen.\(phase) never appeared")
            let shot = XCTAttachment(screenshot: app.screenshot())
            shot.name = phase
            shot.lifetime = .keepAlways
            add(shot)
            try audit(app, screen: phase)
        }
        // Closing the AR view returns to the result.
        XCTAssertTrue(app.descendants(matching: .any)["screen.result"].waitForExistence(timeout: 20), "closing AR did not return to the result")
    }
}
